# Generated by Django 3.2.6 on 2021-08-17 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, unique=True)),
                ('body', models.TextField(max_length=600)),
                ('author', models.TextField(blank=True, max_length=100)),
                ('isPublish', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
